server:
  port: 8001

mybatis:
  type-aliases-package: com.pony.springcloud.pojofig
  mapper-locations: classpath:mybaties/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


spring:
  application:
    name: springcloud-providerUser
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.116.10:3306/pony2?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.2:7001/eureka/,http://127.0.0.1:7003/eureka/
  instance:
    instance-id: provider_8001
info:
  app.name: userProvider
  compony.name: ponykeji
