server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://registerCenter1:7001/eureka/,http://registerCenter3:7003/eureka/,http://registerCenter2:7002/eureka/
    register-with-eureka: false  #不向注册中心注册自己

spring:
  main:
    allow-bean-definition-overriding: true

feign:
  hystrix:
    enabled: true